---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-mlflow-setup
  namespace: mlflow
  # annotations:
  #   argocd.argoproj.io/hook: PreSync
  #   argocd.argoproj.io/hook-delete-policy: HookSucceeded
  #   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-secrets
          image: bitnami/kubectl:latest
          command:
          - /bin/sh
          - -c
          - |
            echo "Waiting for pg-superuser secret..."
            until kubectl get secret pg-superuser -n mlflow; do
              echo "Secret pg-superuser not found, waiting..."
              sleep 5
            done
            echo "Secret pg-superuser found!"
      containers:
      - name: postgresql-setup
        image: postgres:15
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-superuser
              key: password
        command:
        - /bin/bash
        - -c
        - |
          echo "Setting up MLflow database..."

          # Wait for PostgreSQL to be ready
          until pg_isready -h pgsql-cluster-rw.postgresql-cluster.svc -U postgres -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

          # Create MLflow database
          psql -h pgsql-cluster-rw.postgresql-cluster.svc -U postgres -c "CREATE DATABASE mlflow;" || echo "Database mlflow already exists"

          # Create MLflow user
          psql -h pgsql-cluster-rw.postgresql-cluster.svc -U postgres -c "CREATE USER mlflow WITH PASSWORD 'mlflow_password';" || echo "User mlflow already exists"

          # Grant privileges
          psql -h pgsql-cluster-rw.postgresql-cluster.svc -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE mlflow TO mlflow;"

          psql -h pgsql-cluster-rw.postgresql-cluster.svc -U postgres -d mlflow -c "ALTER SCHEMA public OWNER TO mlflow;"

          psql -h pgsql-cluster-rw.postgresql-cluster.svc -U postgres -d mlflow -c "GRANT ALL ON SCHEMA public TO mlflow;"

          psql -h pgsql-cluster-rw.postgresql-cluster.svc -U postgres -d mlflow -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO mlflow;"

          echo "MLflow database setup completed!"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"