apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlflow-secret-reader
  namespace: mlflow
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlflow-secret-reader-binding
  namespace: mlflow
subjects:
  - kind: ServiceAccount
    name: default
    namespace: mlflow
roleRef:
  kind: Role
  name: mlflow-secret-reader
  apiGroup: rbac.authorization.k8s.io